load("//dockerfile:image.bzl", "dockerfile_image")

dockerfile_image(
    name = "alpine-with-packages",
    dockerfile = "Dockerfile",
)

#sh_test(
#    name = "dockerfile_import_test",
#    #    size = "small",
#    srcs = [":alpine-with-packages"],
#    tags = ["local"],
#)
